In [9]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
target1 = stats.uniform.rvs(size=100, random_state=rng)
target2 = stats.norm.rvs(size=110, random_state=rng)
response=stats.ks_2samp(sample1, sample2)

# Generating random samples
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)

# Using the ks_2samp function
result = stats.ks_2samp(sample1, sample2)

In [10]:
sample1

array([0.67575305, 0.4988121 , 0.57911291, 0.03028173, 0.07840431,
       0.72121442, 0.05182883, 0.55376683, 0.68552535, 0.6776308 ,
       0.95794333, 0.2122098 , 0.0220999 , 0.6475089 , 0.95177932,
       0.17799157, 0.33470668, 0.2175791 , 0.15480623, 0.3151129 ,
       0.60334024, 0.38169144, 0.51978622, 0.91399256, 0.32763427,
       0.07456629, 0.28617745, 0.04414099, 0.57552424, 0.2507746 ,
       0.74131766, 0.36717542, 0.92613364, 0.27794678, 0.28899556,
       0.30309798, 0.15113296, 0.30551053, 0.15792789, 0.46945606,
       0.67809719, 0.79394625, 0.29414618, 0.58720355, 0.78683062,
       0.00426723, 0.61104482, 0.18920852, 0.63006677, 0.16276775,
       0.93478692, 0.8979466 , 0.30335884, 0.871756  , 0.64350455,
       0.48563326, 0.73861452, 0.10803873, 0.99784391, 0.18428902,
       0.48274359, 0.3072108 , 0.35718634, 0.97483311, 0.92510501,
       0.44309606, 0.68744338, 0.91236368, 0.23477102, 0.84732327,
       0.36809748, 0.04930297, 0.55511119, 0.16693306, 0.85851279,
       0.66157447, 0.17979844, 0.44853122, 0.12180063, 0.56841078,
       0.23546945, 0.24596893, 0.71643439, 0.69213625, 0.05390422,
       0.73615889, 0.53913946, 0.61143607, 0.87572838, 0.7263041 ,
       0.65078321, 0.91273587, 0.43279999, 0.99182891, 0.48604172,
       0.02711114, 0.91488625, 0.73561064, 0.18095061, 0.289779  ])

In [11]:
sample2

array([-1.2236816 ,  0.21252873,  0.61122638, -0.47464835,  0.296509  ,
        1.4975563 , -0.66686366,  0.67545121,  1.41750881, -0.5365677 ,
       -1.29233197, -1.12887472,  1.60055877, -1.34421831, -0.80861486,
        0.34902683, -1.17704364,  0.62712816,  0.15138504, -0.78431198,
        0.05131544, -1.12092072,  0.57874236,  1.08933226, -0.90030734,
       -0.62807251,  0.526588  , -0.94554774, -0.69130249, -0.06811316,
        0.19893981,  1.61149698,  0.08020106,  1.30965433, -0.84476128,
       -0.24138867, -1.09499036, -0.99790592, -0.64629451, -0.58389574,
        1.32618023,  0.15182251, -0.0589088 , -0.48330789,  1.67139947,
        1.42686082, -0.34162788, -1.11343995, -0.86569101, -1.01210366,
       -0.60200469, -0.58285156, -0.71405354, -0.87736197,  0.25744526,
       -0.2186907 , -0.94410458, -0.81576314,  0.77137967, -1.93351776,
        0.26476023, -1.22564624, -0.26415678, -1.30106498, -0.71829311,
       -0.91129487, -0.23895257, -0.83012039, -1.09393857,  0.02164465,
        0.30581604, -0.13074472, -0.32617909,  1.35474889, -0.106391  ,
       -0.2898852 , -0.03593248, -0.06438025,  0.16644605, -0.19810844,
       -1.57974312, -0.26895736,  0.33413744,  0.090422  , -0.51416842,
       -0.7747622 , -0.88125699, -0.0250805 , -0.99087459,  0.21833724,
       -0.78878651, -1.32245776,  0.92621086,  1.53418183,  1.03674985,
       -0.18736199,  0.73715283,  0.42961875, -1.56868112,  0.95812117,
        0.06479598,  1.58599839, -0.05269427, -1.22888395,  0.65420179,
        0.5648896 ,  2.05106656, -0.77299501, -0.82052964,  0.81628212])

In [12]:
round(response.pvalue)

0

In [22]:
# Anomaly in my dataset
# 
# 1. High Null Value
# 2. Missing Columns
# 3. Outliers
# 4. Categorical:
#    Gender --> MALE, FEMALE, OTHER

In [23]:
import pandas as pd

In [24]:
l1=[1,2,3,4]
l2=[4,5,6,7]

for l1_val,l2_val in zip(l1,l2):
    print(l1_val,l2_val)

1 4
2 5
3 6
4 7

In [25]:
df=pd.read_csv("/config/workspace/aps_failure_training_set1.csv")

In [26]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)

0

In [27]:
null_report=df.isna().sum()/df.shape[0]

In [28]:
for column_name,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index,(df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)
    if missing_percentage>0.3:
        drop_column_names.append(column_name)

class 0.0
aa_000 0.0
ab_000 0.0
ac_000 0.0
ad_000 0.0
ae_000 0.0
af_000 0.0
ag_000 0.0
ag_001 0.0
ag_002 0.0
ag_003 0.0
ag_004 0.0
ag_005 0.0
ag_006 0.0
ag_007 0.0
ag_008 0.0
ag_009 0.0
ah_000 0.0
ai_000 0.0
aj_000 0.0
ak_000 0.0
al_000 0.0
am_0 0.0
an_000 0.0
ao_000 0.0
ap_000 0.0
aq_000 0.0
ar_000 0.0
as_000 0.0
at_000 0.0
au_000 0.0
av_000 0.0
ax_000 0.0
ay_000 0.0
ay_001 0.0
ay_002 0.0
ay_003 0.0
ay_004 0.0
ay_005 0.0
ay_006 0.0
ay_007 0.0
ay_008 0.0
ay_009 0.0
az_000 0.0
az_001 0.0
az_002 0.0
az_003 0.0
az_004 0.0
az_005 0.0
az_006 0.0
az_007 0.0
az_008 0.0
az_009 0.0
ba_000 0.0
ba_001 0.0
ba_002 0.0
ba_003 0.0
ba_004 0.0
ba_005 0.0
ba_006 0.0
ba_007 0.0
ba_008 0.0
ba_009 0.0
bb_000 0.0
bc_000 0.0
bd_000 0.0
be_000 0.0
bf_000 0.0
bg_000 0.0
bh_000 0.0
bi_000 0.0
bj_000 0.0
bk_000 0.0
bl_000 0.0
bm_000 0.0
bn_000 0.0
bo_000 0.0
bp_000 0.0
bq_000 0.0
br_000 0.0
bs_000 0.0
bt_000 0.0
bu_000 0.0
bv_000 0.0
bx_000 0.0
by_000 0.0
bz_000 0.0
ca_000 0.0
cb_000 0.0
cc_000 0.0
cd_000 0.0
ce_000 0.0
cf_000 0.0
cg_000 0.0
ch_000 0.0
ci_000 0.0
cj_000 0.0
ck_000 0.0
cl_000 0.0
cm_000 0.0
cn_000 0.0
cn_001 0.0
cn_002 0.0
cn_003 0.0
cn_004 0.0
cn_005 0.0
cn_006 0.0
cn_007 0.0
cn_008 0.0
cn_009 0.0
co_000 0.0
cp_000 0.0
cq_000 0.0
cr_000 0.0
cs_000 0.0
cs_001 0.0
cs_002 0.0
cs_003 0.0
cs_004 0.0
cs_005 0.0
cs_006 0.0
cs_007 0.0
cs_008 0.0
cs_009 0.0
ct_000 0.0
cu_000 0.0
cv_000 0.0
cx_000 0.0
cy_000 0.0
cz_000 0.0
da_000 0.0
db_000 0.0
dc_000 0.0
dd_000 0.0
de_000 0.0
df_000 0.0
dg_000 0.0
dh_000 0.0
di_000 0.0
dj_000 0.0
dk_000 0.0
dl_000 0.0
dm_000 0.0
dn_000 0.0
do_000 0.0
dp_000 0.0
dq_000 0.0
dr_000 0.0
ds_000 0.0
dt_000 0.0
du_000 0.0
dv_000 0.0
dx_000 0.0
dy_000 0.0
dz_000 0.0
ea_000 0.0
eb_000 0.0
ec_00 0.0
ed_000 0.0
ee_000 0.0
ee_001 0.0
ee_002 0.0
ee_003 0.0
ee_004 0.0
ee_005 0.0
ee_006 0.0
ee_007 0.0
ee_008 0.0
ee_009 0.0
ef_000 0.0
eg_000 0.0

In [29]:
null_report = df.isna().sum()/df.shape[0]
null_report[null_report>0.3].index

Index([], dtype='object')

In [30]:
null_report[null_report>0.3].index

Index([], dtype='object')

In [31]:
df.replace("/config/workspace/artifact/05292023__212341/dataset/train.csv")

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,pos,153204,0,182,na,0,0,0,0,0,...,129862,26872,34044,22472,34362,0,0,0,0,0
1,pos,453236,na,2926,na,0,0,0,0,222,...,7908038,3026002,5025350,2025766,1160638,533834,493800,6914,0,0
2,pos,72504,na,1594,1052,0,0,0,244,178226,...,1432098,372252,527514,358274,332818,284178,3742,0,0,0
3,pos,762958,na,na,na,na,na,776,281128,2186308,...,na,na,na,na,na,na,na,na,na,na
4,pos,695994,na,na,na,na,na,0,0,0,...,1397742,495544,361646,28610,5130,212,0,0,na,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36183,neg,153002,na,664,186,0,0,0,0,0,...,998500,566884,1290398,1218244,1019768,717762,898642,28588,0,0
36184,neg,2286,na,2130706538,224,0,0,0,0,0,...,10578,6760,21126,68424,136,0,0,0,0,0
36185,neg,112,0,2130706432,18,0,0,0,0,0,...,792,386,452,144,146,2622,0,0,0,0
36186,neg,80292,na,2130706432,494,0,0,0,0,0,...,699352,222654,347378,225724,194440,165070,802280,388422,0,0
36187,neg,40222,na,698,628,0,0,0,0,0,...,440066,183200,344546,254068,225148,158304,170384,158,0,0